[package]
name = "gmf-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json","rustls-tls"] }
tokio = { version = "1", features = ["rt-multi-thread","macros","time"] }

gmf-core = { path = "../../core/gmf-core" }
