[workspace]
resolver = "2"
members = [
  "gmf_export_audit_final_verify",
  "gmf_canonical_export_verify",
  "gmf_report_verify",
  "gmf_meta_audit_final_verify",
  "gmf_audit_final_verify",
  "gmf_final_verify",
  "gmf_receipts",
  "gmf_ledger",
  "gmf_worker"
]
