[package]
name = "gmf_android_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmf-core = { path = "../../../../core/gmf-core" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread","macros","time"] }
once_cell = "1"
