name: publish-pages
on:
  push:
    paths:
      - releases/appcast.xml
      - releases/**

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare pages content
        run: |
          mkdir -p _pages/releases
          cp -rf releases/. _pages/releases/ || true
          mkdir -p _pages/releases/windows
          cp -rf releases/windows/. _pages/releases/windows/ || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _pages
